######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 28 10:55:39 2010
######################################################################

TEMPLATE = app
TARGET = ui
DEPENDPATH += .
INCLUDEPATH += .

QT += core gui declarative

# Input
HEADERS += pad.h
SOURCES += main.cpp pad.cpp
