ALL :
	python2.5 -OO -m py_compile ui/*.py
	python2.5 -OO -m py_compile pinyinLookup/*.py
	python2.5 -OO -m py_compile utils/*.py
	python2.5 -OO -m py_compile qwert/*.py

clean :
	rm ui/*.pyo
	rm pinyinLookup/*.pyo
	rm utils/*.pyo
	rm qwert/*.pyo
